services:
  malaria-mensal-ewars:
    build: https://github.com/fernandoinacio/chapkit_ewars_model.git
    ports:
      - "8001:8000"
    environment:
      - SERVICEKIT_ORCHESTRATOR_URL=http://chap:8000
      - CHAP_CORE_URL=http://chap:8000
