[project]
name = "chapkit-ewars-malaria"
version = "1.0.0"
description = "Uma re-adaptação do modelo EWARS da OMS, desenvolvido pela equipe CHAP core. Este modelo é uma implementação para modelagem e previsão de casos de malária"
requires-python = ">=3.13"
dependencies = ["chapkit>=1.0.0"]

[dependency-groups]
dev = [
    "ruff>=0.15.17",
]

[tool.ruff]
target-version = "py313"
line-length = 120

[tool.ruff.lint]
fixable = ["ALL"]
select = ["E", "W", "F", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
